# Generated by Django 2.0.1 on 2018-01-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entradas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_apertura', models.DateTimeField()),
                ('f_cierre', models.DateTimeField()),
                ('f_modificado', models.DateTimeField()),
                ('estado', models.CharField(max_length=200)),
                ('ticket', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('divisa', models.DecimalField(decimal_places=5, max_digits=6)),
                ('stop', models.DecimalField(decimal_places=5, max_digits=11)),
                ('n_acciones', models.IntegerField()),
                ('comision_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comision_v', models.DecimalField(decimal_places=2, max_digits=5)),
                ('p_compra', models.DecimalField(decimal_places=5, max_digits=8)),
                ('p_venta', models.DecimalField(decimal_places=5, max_digits=8)),
                ('p_actual', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
    ]
